apiVersion: v1
kind: Service
metadata:
    name: "backstageaks-e2b6"
    labels:
        app: "backstageaks-e2b6"
spec:
    type: LoadBalancer
    ports:
    - port: 7007
      targetPort: 7007
      protocol: TCP
      name: http
    selector:
        app: "backstageaks-e2b6"