on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n newacrkube -g newacrkube8d2b-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n newacrkube --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n newacrkube --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n newacrkube --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: newacrkube.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/root" -f  "packages/backend" -t newacrkube.azurecr.io/backstageaks:${{ github.sha }} --label dockerfile-path=packages/backend
        docker push newacrkube.azurecr.io/backstageaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_backstageaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep backstageaksgithub | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace backstageaksgithub`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: backstageaksgithub
        container-registry-url: newacrkube.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: backstageaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: backstageaksgithub
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          newacrkube.azurecr.io/backstageaks:${{ github.sha }}
        imagepullsecrets: |
          backstageaksdockerauth   
